version: "3.8"
services:
  repro_4-2:
    build: .
    network_mode: "host"
    environment:
      - SNAPSHOT_DATE=2023-05-25
      - PYTHON_VERSION=3.11.3
    volumes:
       - ./output:/usr/local/src/output # [local path]:[container path]
