version: "3.8"
services:
  repro_4-2:
    build: .
    network_mode: "host"
    environment:
      - SNAPSHOT_DATE=${SNAPSHOT_DATE}
      - PYTHON_VERSION=3.11.3
      - PROJECT_NODE=${PROJECT_NODE}
      - OSF_PAT=${OSF_PAT}
    volumes:
      - ./output:/usr/local/src/output # [local path]:[container path]
