version: "3.8"
services:
  repro_4-2:
    build: .
    network_mode: "host"
    environment:
    # there is an issue with inca that keeps it from installing, chaning to an older data and python version resolves it
      - SNAPSHOT_DATE=2021-12-16
    # for interactive use, I leave the container running during development
    command: tail -f /dev/null
    volumes:
       - ./output:/usr/local/src/output # [local path]:[container path]
